title = "Andrew J. Camenga"
baseURL = ""
copyright = "&copy;{year}"
timeZone = "America/New_York"

defaultContentLanguage = "en"
languageCode = "en-us"
removePathAccents = true

theme = "ajc"

[permalinks]
note = "/note/:2006-:01-:02-:1504"

[markup.goldmark.renderer]
unsafe= true

[taxonomies]
  category = "categories"
  topic = "topics"