title = "Andrew J. Camenga"
baseURL = ""
copyright = "&copy;{year}"

defaultContentLanguage = "en"
languageCode = "en-us"
removePathAccents = true

theme = "ajc"

[permalinks]
    note = "/note/:20060102-:150406"

