[build]
  command = "hugo --gc -b $URL"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.148.2"
  HUGO_ENABLEGITINFO = "true"
  # see index.js for default value
  DART_SASS_VERSION = "1.90.0" 

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc -b $DEPLOY_PRIME_URL"

[[plugins]]
  package = "@gethinode/netlify-plugin-dartsass"
